# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js apps to Azure Web Apps - EvalFrontDevGit and EvalFrontTestGit

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: |
          cd dist/
          zip ../release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp-prod.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Set environment variables for Dev
        run: echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL_DEV }}" >> $GITHUB_ENV
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EBC7E00BCDDB45CFAB1CB44E222F3565 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C7052FF9DA9B4A549D297975BA2046B2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_22ABBDF97A6D43438144903F0664F335 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp-prod
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'EvalFrontDevGit'
          slot-name: 'Production'
          package: .

  deploy-to-test:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp-test.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Set environment variables for Test
        run: echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL_TEST }}" >> $GITHUB_ENV
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9D70B66A6AE5444CAAFA6643B63881FF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_49735694C73F4CABA4D88C0B94D94928 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B96327DE864948BF9968A78E96FEBDC2 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp-test
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'EvalFrontTestGit'
          slot-name: 'Production'
          package: .
          
  deploy-to-prod:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Set environment variables for Prod
        run: echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL_PROD }}" >> $GITHUB_ENV
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_99167A5443874C5FA80D3D979141CF73 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6D04185749854F0BBDF5017375E64054 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_50EBDCF2CF6D48F2994F63F6DE3B6622 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'EvalFrontProGit'
          slot-name: 'Production'
          package: .
